### PR TITLE
Cleaned up message grammar

### PR DESCRIPTION
**Pull request by Doormatty**
Edited the text snippets in Messages.js for clarity and grammar.

### CODE REVIEW

**Comment by Doormatty** [comment]
I figured you'd complain if I changed anything important!

>Alchemist is one person, so line about legend about him should indicate that (the ending s is not right I think)

Got it.  Are there multiple legends about him, or just one legend?

>mentor/scholars vs teacher/doctors. 

No problem- wasn't sure if it was by design or not - I'll undo that!

>inventory can be used as a verb? 

Yup!  You can say "I took inventory of my belongings" or "While inventorying my backpack, I noticed..." or "While taking inventory of my..."

>"surprised I walk back into the room"

I get what you were trying to say now!  I'll try again.

>reaction catalyst part is important. Protagonist did not made it, it only activated by itself in the middle of the room. I want to preserve that context somehow

Got it.  A few questions/issues.  

Was this device just always there, it just was unnoticed by the protagonist until it activated?

**Comment by Doormatty** [comment]
Also - do you really mean implosion?   (like a submarine crushed by water pressure)

Explosion (bomb) is what I would expect you to mean, but maybe I'm picturing it wrong.

**Comment by Nagshell** [comment]
Yes, device was always there but it was inactive and thus unnoticed

We can safely assume there are multiple legends about him. And they are very old, but generations of people using Elemental Arts kept them alive.

**Comment by Nagshell** [comment]
Yes, I think I stated that it was implosion followed by explosion-like wave of Elements. Wave is the force that affects a world around it while Orb themselves implode aka get much much smaller in a short amount of time.

What I maybe didn't make clear that after the whole process Orbs slowly recovered back to almost original size

**Comment by Doormatty** [comment]
>implosion followed by explosion-like wave of Elements.

Gotcha!

Can you explain the lore in outro1 further?   I'm just not 100% sure what you mean by:

>I tried it before, but it was a complete failure, the interactions between the elements caused all the Orbs to empty themselves.   

If it's been tried before, why do we think it will be different this time?

**Comment by Nagshell** [comment]
Stage 1 and 2 will be redone after the release of Stage 3

**Pull request closed without merging**
