### PR TITLE
Minor typo corrections

### PR DESCRIPTION
**Pull request by thunderrabbit**
I will stop for now.  I think any other English fixes will change the voice of the narrator.

### CODE REVIEW

**Comment by Nagshell** [comment]
Thank you for your work.
"Let's" is never correct, right? It always should be "Lets"?

**Comment by ThePhantomLemon** [comment]
No, "Let's" is correct if you're trying to say "Let us". 

"Let's consider all the facts." vs "The vent lets air in."

**Comment by Nagshell** [comment]
Alright.

So as the story tries to be about only one character and his inner thoughts I have changed all let's into lets. He just motivates himself to push further.

**Comment by thunderrabbit** [comment]
With no apostrophe, **lets** means **allows**.

Most of the time in your story, **let's** was correct.  If you want to just have him motivating himself, you can use **I will**.

**I will** can be shortened into **I'll**.

**Comment by Nagshell** [comment]
Engrish is hard. I'm playtesting new message system. If I can complete playthrough then I'll upload message file.

Would you be so kind to check it out and propose any changes to make it better in terms of writing?

**Pull request merged**
